version: '3'
services:
  web:
    container_name: web-server-nginx
    image: nginx:latest
    networks:
      - adoptme-net
    ports:
      - '8080:80'
    volumes:
      - ./web:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  
  php-fpm:
    container_name: php8.1-fpm
    image: php:8.1-fpm
    networks:
      - adoptme-net
    volumes:
      - ./web:/var/www/html

  api:
    container_name: api-rest-nodejs-express
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    networks:
      - adoptme-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3000:3000
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    
  db:
    container_name: db-mariadb
    image: mariadb
    environment:
      - MYSQL_DATABASE=adoptme
      - MYSQL_USER=adoptme-admin
      - MYSQL_PASSWORD=adoptme-password
      - MYSQL_ROOT_PASSWORD=rootroot
    restart: always
    networks:
      - adoptme-net
    ports:
      - 3306:3306
    volumes:
      - ./db/adoptme.sql:/docker-entrypoint-initdb.d/schema.sql:ro
  
networks:
  adoptme-net: